# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TEST CI

name: CI Build User Interface

on:
  push:
    branches:
      - stable
  workflow_dispatch:
jobs:
  build:
    env:
      VITE_AUTH_HOST: https://auth.corps.cloud/auth
      VITE_AUTH_REDIRECT_URL: https://workforce.corps.cloud
      VITE_WORKFORCE_API_URL: https://workforce-api.corps.cloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: Deploy to Dev
        env:
          AWS_REGION: ${{ secrets.CASTLECI_STABLE_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CASTLECI_STABLE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CASTLECI_STABLE_AWS_SECRET_ACCESS_KEY }}
          CASTLECI_STABLE_S3_BUCKET_APPS: ${{ secrets.CASTLECI_STABLE_S3_BUCKET_APPS}}
        run: npm run deploy-stable
